package com.boir.sdk.enums;

import com.boir.sdk.enums.model.EnumModel;

import java.util.ArrayList;

public class ForeignCountriesEnum {

    public static final EnumModel VALUE1 = new EnumModel("AF", "Afghanistan (AF)");
    public static final EnumModel VALUE2 = new EnumModel("AX", "Åland Islands (AX)");
    public static final EnumModel VALUE3 = new EnumModel("AL", "Albania (AL)");
    public static final EnumModel VALUE4 = new EnumModel("DZ", "Algeria (DZ)");
    public static final EnumModel VALUE5 = new EnumModel("AD", "Andorra (AD)");
    public static final EnumModel VALUE6 = new EnumModel("AO", "Angola (AO)");
    public static final EnumModel VALUE7 = new EnumModel("AI", "Anguilla (AI)");
    public static final EnumModel VALUE8 = new EnumModel("AQ", "Antarctica (AQ)");
    public static final EnumModel VALUE9 = new EnumModel("AG", "Antigua And Barbuda (AG)");
    public static final EnumModel VALUE10 = new EnumModel("AR", "Argentina (AR)");
    public static final EnumModel VALUE11 = new EnumModel("AM", "Armenia (AM)");
    public static final EnumModel VALUE12 = new EnumModel("AW", "Aruba (AW)");
    public static final EnumModel VALUE13 = new EnumModel("AU", "Australia (AU)");
    public static final EnumModel VALUE14 = new EnumModel("AT", "Austria (AT)");
    public static final EnumModel VALUE15 = new EnumModel("AZ", "Azerbaijan (AZ)");
    public static final EnumModel VALUE16 = new EnumModel("BS", "Bahamas (BS)");
    public static final EnumModel VALUE17 = new EnumModel("BH", "Bahrain (BH)");
    public static final EnumModel VALUE18 = new EnumModel("BD", "Bangladesh (BD)");
    public static final EnumModel VALUE19 = new EnumModel("BB", "Barbados (BB)");
    public static final EnumModel VALUE20 = new EnumModel("BY", "Belarus (BY)");
    public static final EnumModel VALUE21 = new EnumModel("BE", "Belgium (BE)");
    public static final EnumModel VALUE22 = new EnumModel("BZ", "Belize (BZ)");
    public static final EnumModel VALUE23 = new EnumModel("BJ", "Benin (BJ)");
    public static final EnumModel VALUE24 = new EnumModel("BM", "Bermuda (BM)");
    public static final EnumModel VALUE25 = new EnumModel("BT", "Bhutan (BT)");
    public static final EnumModel VALUE26 = new EnumModel("BO", "Bolivia (Plurinational State of) (BO)");
    public static final EnumModel VALUE27 = new EnumModel("BQ", "Bonaire, Sint Eustatius And Saba (BQ)");
    public static final EnumModel VALUE28 = new EnumModel("BA", "Bosnia And Herzegovina (BA)");
    public static final EnumModel VALUE29 = new EnumModel("BW", "Botswana (BW)");
    public static final EnumModel VALUE30 = new EnumModel("BV", "Bouvet Island (BV)");
    public static final EnumModel VALUE31 = new EnumModel("BR", "Brazil (BR)");
    public static final EnumModel VALUE32 = new EnumModel("IO", "British Indian Ocean Territory (IO)");
    public static final EnumModel VALUE33 = new EnumModel("BN", "Brunei Darussalam (BN)");
    public static final EnumModel VALUE34 = new EnumModel("BG", "Bulgaria (BG)");
    public static final EnumModel VALUE35 = new EnumModel("BF", "Burkina Faso (BF)");
    public static final EnumModel VALUE36 = new EnumModel("BI", "Burundi (BI)");
    public static final EnumModel VALUE37 = new EnumModel("KH", "Cambodia (KH)");
    public static final EnumModel VALUE38 = new EnumModel("CM", "Cameroon (CM)");
    public static final EnumModel VALUE39 = new EnumModel("CA", "Canada (CA)");
    public static final EnumModel VALUE40 = new EnumModel("CV", "Cape Verde (CV)");
    public static final EnumModel VALUE41 = new EnumModel("KY", "Cayman Islands (KY)");
    public static final EnumModel VALUE42 = new EnumModel("CF", "Central African Republic (CF)");
    public static final EnumModel VALUE43 = new EnumModel("TD", "Chad (TD)");
    public static final EnumModel VALUE44 = new EnumModel("CL", "Chile (CL)");
    public static final EnumModel VALUE45 = new EnumModel("CN", "China (CN)");
    public static final EnumModel VALUE46 = new EnumModel("CX", "Christmas Island (CX)");
    public static final EnumModel VALUE47 = new EnumModel("CC", "Cocos (Keeling) Islands (CC)");
    public static final EnumModel VALUE48 = new EnumModel("CO", "Colombia (CO)");
    public static final EnumModel VALUE49 = new EnumModel("KM", "Comoros (KM)");
    public static final EnumModel VALUE50 = new EnumModel("CG", "Congo (CG)");
    public static final EnumModel VALUE51 = new EnumModel("CD", "Congo, The Democratic Republic Of The (CD)");
    public static final EnumModel VALUE52 = new EnumModel("CK", "Cook Islands (CK)");
    public static final EnumModel VALUE53 = new EnumModel("CR", "Costa Rica (CR)");
    public static final EnumModel VALUE54 = new EnumModel("CI", "Côte D'ivoire (CI)");
    public static final EnumModel VALUE55 = new EnumModel("HR", "Croatia (HR)");
    public static final EnumModel VALUE56 = new EnumModel("CU", "Cuba (CU)");
    public static final EnumModel VALUE57 = new EnumModel("CW", "Curaçao (CW)");
    public static final EnumModel VALUE58 = new EnumModel("CY", "Cyprus (CY)");
    public static final EnumModel VALUE59 = new EnumModel("(CZ", "Czech Republic ((CZ)");
    public static final EnumModel VALUE60 = new EnumModel("DK", "Denmark (DK)");
    public static final EnumModel VALUE61 = new EnumModel("DJ", "Djibouti (DJ)");
    public static final EnumModel VALUE62 = new EnumModel("DM", "Dominica (DM)");
    public static final EnumModel VALUE63 = new EnumModel("DO", "Dominican Republic (DO)");
    public static final EnumModel VALUE64 = new EnumModel("EC", "Ecuador (EC)");
    public static final EnumModel VALUE65 = new EnumModel("EG", "Egypt (EG)");
    public static final EnumModel VALUE66 = new EnumModel("SV", "El Salvador (SV)");
    public static final EnumModel VALUE67 = new EnumModel("GQ", "Equatorial Guinea (GQ)");
    public static final EnumModel VALUE68 = new EnumModel("ER", "Eritrea (ER)");
    public static final EnumModel VALUE69 = new EnumModel("EE", "Estonia (EE)");
    public static final EnumModel VALUE70 = new EnumModel("ET", "Ethiopia (ET)");
    public static final EnumModel VALUE71 = new EnumModel("FK", "Falkland Islands (Malvinas) (FK)");
    public static final EnumModel VALUE72 = new EnumModel("FO", "Faroe Islands (FO)");
    public static final EnumModel VALUE73 = new EnumModel("FJ", "Fiji (FJ)");
    public static final EnumModel VALUE74 = new EnumModel("FI", "Finland (FI)");
    public static final EnumModel VALUE75 = new EnumModel("FR", "France (FR)");
    public static final EnumModel VALUE76 = new EnumModel("GF", "French Guiana (GF)");
    public static final EnumModel VALUE77 = new EnumModel("PF", "French Polynesia (PF)");
    public static final EnumModel VALUE78 = new EnumModel("TF", "French Southern Territories (TF)");
    public static final EnumModel VALUE79 = new EnumModel("GA", "Gabon (GA)");
    public static final EnumModel VALUE80 = new EnumModel("GM", "Gambia (GM)");
    public static final EnumModel VALUE81 = new EnumModel("GE", "Georgia (GE)");
    public static final EnumModel VALUE82 = new EnumModel("DE", "Germany (DE)");
    public static final EnumModel VALUE83 = new EnumModel("GH", "Ghana (GH)");
    public static final EnumModel VALUE84 = new EnumModel("GI", "Gibraltar (GI)");
    public static final EnumModel VALUE85 = new EnumModel("GR", "Greece (GR)");
    public static final EnumModel VALUE86 = new EnumModel("GL", "Greenland (GL)");
    public static final EnumModel VALUE87 = new EnumModel("GD", "Grenada (GD)");
    public static final EnumModel VALUE88 = new EnumModel("GP", "Guadeloupe (GP)");
    public static final EnumModel VALUE89 = new EnumModel("GT", "Guatemala (GT)");
    public static final EnumModel VALUE90 = new EnumModel("GG", "Guernsey (GG)");
    public static final EnumModel VALUE91 = new EnumModel("GN", "Guinea (GN)");
    public static final EnumModel VALUE92 = new EnumModel("GW", "Guinea-bissau (GW)");
    public static final EnumModel VALUE93 = new EnumModel("GY", "Guyana (GY)");
    public static final EnumModel VALUE94 = new EnumModel("HT", "Haiti (HT)");
    public static final EnumModel VALUE95 = new EnumModel("HM", "Heard Island And Mcdonald Islands (HM)");
    public static final EnumModel VALUE96 = new EnumModel("VA", "Holy See (VA)");
    public static final EnumModel VALUE97 = new EnumModel("HN", "Honduras (HN)");
    public static final EnumModel VALUE98 = new EnumModel("HK", "Hong Kong (HK)");
    public static final EnumModel VALUE99 = new EnumModel("HU", "Hungary (HU)");
    public static final EnumModel VALUE100 = new EnumModel("IS", "Iceland (IS)");
    public static final EnumModel VALUE101 = new EnumModel("IN", "India (IN)");
    public static final EnumModel VALUE102 = new EnumModel("ID", "Indonesia (ID)");
    public static final EnumModel VALUE103 = new EnumModel("IR", "Iran, Islamic Republic Of (IR)");
    public static final EnumModel VALUE104 = new EnumModel("IQ", "Iraq (IQ)");
    public static final EnumModel VALUE105 = new EnumModel("IE", "Ireland (IE)");
    public static final EnumModel VALUE106 = new EnumModel("IM", "Isle Of Man (IM)");
    public static final EnumModel VALUE107 = new EnumModel("IL", "Israel (IL)");
    public static final EnumModel VALUE108 = new EnumModel("IT", "Italy (IT)");
    public static final EnumModel VALUE109 = new EnumModel("JM", "Jamaica (JM)");
    public static final EnumModel VALUE110 = new EnumModel("JP", "Japan (JP)");
    public static final EnumModel VALUE111 = new EnumModel("JE", "Jersey (JE)");
    public static final EnumModel VALUE112 = new EnumModel("JO", "Jordan (JO)");
    public static final EnumModel VALUE113 = new EnumModel("KZ", "Kazakhstan (KZ)");
    public static final EnumModel VALUE114 = new EnumModel("KE", "Kenya (KE)");
    public static final EnumModel VALUE115 = new EnumModel("KI", "Kiribati (KI)");
    public static final EnumModel VALUE116 = new EnumModel("KP", "Korea, Democratic People's Republic Of (KP)");
    public static final EnumModel VALUE117 = new EnumModel("KR", "Korea, Republic Of (KR)");
    public static final EnumModel VALUE118 = new EnumModel("KW", "Kuwait (KW)");
    public static final EnumModel VALUE119 = new EnumModel("KG", "Kyrgyzstan (KG)");
    public static final EnumModel VALUE120 = new EnumModel("LA", "Lao People's Democratic Republic (LA)");
    public static final EnumModel VALUE121 = new EnumModel("LV", "Latvia (LV)");
    public static final EnumModel VALUE122 = new EnumModel("LB", "Lebanon (LB)");
    public static final EnumModel VALUE123 = new EnumModel("LS", "Lesotho (LS)");
    public static final EnumModel VALUE124 = new EnumModel("LR", "Liberia (LR)");
    public static final EnumModel VALUE125 = new EnumModel("LY", "Libya (LY)");
    public static final EnumModel VALUE126 = new EnumModel("LI", "Liechtenstein (LI)");
    public static final EnumModel VALUE127 = new EnumModel("LT", "Lithuania (LT)");
    public static final EnumModel VALUE128 = new EnumModel("LU", "Luxembourg (LU)");
    public static final EnumModel VALUE129 = new EnumModel("MO", "Macao (MO)");
    public static final EnumModel VALUE130 = new EnumModel("MK", "Macedonia, The Former Yugoslav Republic Of (MK)");
    public static final EnumModel VALUE131 = new EnumModel("MG", "Madagascar (MG)");
    public static final EnumModel VALUE132 = new EnumModel("MW", "Malawi (MW)");
    public static final EnumModel VALUE133 = new EnumModel("MY", "Malaysia (MY)");
    public static final EnumModel VALUE134 = new EnumModel("MV", "Maldives (MV)");
    public static final EnumModel VALUE135 = new EnumModel("ML", "Mali (ML)");
    public static final EnumModel VALUE136 = new EnumModel("MT", "Malta (MT)");
    public static final EnumModel VALUE137 = new EnumModel("MQ", "Martinique (MQ)");
    public static final EnumModel VALUE138 = new EnumModel("MR", "Mauritania (MR)");
    public static final EnumModel VALUE139 = new EnumModel("MU", "Mauritius (MU)");
    public static final EnumModel VALUE140 = new EnumModel("YT", "Mayotte (YT)");
    public static final EnumModel VALUE141 = new EnumModel("MX", "Mexico (MX)");
    public static final EnumModel VALUE142 = new EnumModel("MD", "Moldova (MD)");
    public static final EnumModel VALUE143 = new EnumModel("MC", "Monaco (MC)");
    public static final EnumModel VALUE144 = new EnumModel("MN", "Mongolia (MN)");
    public static final EnumModel VALUE145 = new EnumModel("ME", "Montenegro (ME)");
    public static final EnumModel VALUE146 = new EnumModel("MS", "Montserrat (MS)");
    public static final EnumModel VALUE147 = new EnumModel("MA", "Morocco (MA)");
    public static final EnumModel VALUE148 = new EnumModel("MZ", "Mozambique (MZ)");
    public static final EnumModel VALUE149 = new EnumModel("MM", "Myanmar (MM)");
    public static final EnumModel VALUE150 = new EnumModel("NA", "Namibia (NA)");
    public static final EnumModel VALUE151 = new EnumModel("NR", "Nauru (NR)");
    public static final EnumModel VALUE152 = new EnumModel("NP", "Nepal (NP)");
    public static final EnumModel VALUE153 = new EnumModel("NL", "Netherlands (NL)");
    public static final EnumModel VALUE154 = new EnumModel("NC", "New Caledonia (NC)");
    public static final EnumModel VALUE155 = new EnumModel("NZ", "New Zealand (NZ)");
    public static final EnumModel VALUE156 = new EnumModel("NI", "Nicaragua (NI)");
    public static final EnumModel VALUE157 = new EnumModel("NE", "Niger (NE)");
    public static final EnumModel VALUE158 = new EnumModel("NG", "Nigeria (NG)");
    public static final EnumModel VALUE159 = new EnumModel("NU", "Niue (NU)");
    public static final EnumModel VALUE160 = new EnumModel("NF", "Norfolk Island (NF)");
    public static final EnumModel VALUE161 = new EnumModel("NO", "Norway (NO)");
    public static final EnumModel VALUE162 = new EnumModel("OM", "Oman (OM)");
    public static final EnumModel VALUE163 = new EnumModel("PK", "Pakistan (PK)");
    public static final EnumModel VALUE164 = new EnumModel("PS", "Palestine (PS)");
    public static final EnumModel VALUE165 = new EnumModel("PA", "Panama (PA)");
    public static final EnumModel VALUE166 = new EnumModel("PG", "Papua New Guinea (PG)");
    public static final EnumModel VALUE167 = new EnumModel("PY", "Paraguay (PY)");
    public static final EnumModel VALUE168 = new EnumModel("PE", "Peru (PE)");
    public static final EnumModel VALUE169 = new EnumModel("PH", "Philippines (PH)");
    public static final EnumModel VALUE170 = new EnumModel("PN", "Pitcairn (PN)");
    public static final EnumModel VALUE171 = new EnumModel("PL", "Poland (PL)");
    public static final EnumModel VALUE172 = new EnumModel("PT", "Portugal (PT)");
    public static final EnumModel VALUE173 = new EnumModel("QA", "Qatar (QA)");
    public static final EnumModel VALUE174 = new EnumModel("RE", "Réunion (RE)");
    public static final EnumModel VALUE175 = new EnumModel("RO", "Romania (RO)");
    public static final EnumModel VALUE176 = new EnumModel("RU", "Russian Federation (RU)");
    public static final EnumModel VALUE177 = new EnumModel("RW", "Rwanda (RW)");
    public static final EnumModel VALUE178 = new EnumModel("BL", "Saint Barthélemy (BL)");
    public static final EnumModel VALUE179 = new EnumModel("SH", "Saint Helena, Ascension and Tristan Da Cunha (SH)");
    public static final EnumModel VALUE180 = new EnumModel("KN", "Saint Kitts And Nevis (KN)");
    public static final EnumModel VALUE181 = new EnumModel("LC", "Saint Lucia (LC)");
    public static final EnumModel VALUE182 = new EnumModel("MF", "Saint Martin (french Part) (MF)");
    public static final EnumModel VALUE183 = new EnumModel("PM", "Saint Pierre And Miquelon (PM)");
    public static final EnumModel VALUE184 = new EnumModel("VC", "Saint Vincent And The Grenadines (VC)");
    public static final EnumModel VALUE185 = new EnumModel("WS", "Samoa (WS)");
    public static final EnumModel VALUE186 = new EnumModel("SM", "San Marino (SM)");
    public static final EnumModel VALUE187 = new EnumModel("ST", "Sao Tome And Principe (ST)");
    public static final EnumModel VALUE188 = new EnumModel("SA", "Saudi Arabia (SA)");
    public static final EnumModel VALUE189 = new EnumModel("SN", "Senegal (SN)");
    public static final EnumModel VALUE190 = new EnumModel("RS", "Serbia (RS)");
    public static final EnumModel VALUE191 = new EnumModel("SC", "Seychelles (SC)");
    public static final EnumModel VALUE192 = new EnumModel("SL", "Sierra Leone (SL)");
    public static final EnumModel VALUE193 = new EnumModel("SG", "Singapore (SG)");
    public static final EnumModel VALUE194 = new EnumModel("SX", "Sint Maarten (dutch Part) (SX)");
    public static final EnumModel VALUE195 = new EnumModel("SK", "Slovakia (SK)");
    public static final EnumModel VALUE196 = new EnumModel("SI", "Slovenia (SI)");
    public static final EnumModel VALUE197 = new EnumModel("SB", "Solomon Islands (SB)");
    public static final EnumModel VALUE198 = new EnumModel("SO", "Somalia (SO)");
    public static final EnumModel VALUE199 = new EnumModel("ZA", "South Africa (ZA)");
    public static final EnumModel VALUE200 = new EnumModel("GS", "South Georgia And The South Sandwich Islands (GS)");
    public static final EnumModel VALUE201 = new EnumModel("SS", "South Sudan (SS)");
    public static final EnumModel VALUE202 = new EnumModel("ES", "Spain (ES)");
    public static final EnumModel VALUE203 = new EnumModel("LK", "Sri Lanka (LK)");
    public static final EnumModel VALUE204 = new EnumModel("SD", "Sudan (SD)");
    public static final EnumModel VALUE205 = new EnumModel("SR", "Suriname (SR)");
    public static final EnumModel VALUE206 = new EnumModel("SJ", "Svalbard And Jan Mayen (SJ)");
    public static final EnumModel VALUE207 = new EnumModel("CH", "Swaziland (CH)");
    public static final EnumModel VALUE208 = new EnumModel("SE", "Sweden (SE)");
    public static final EnumModel VALUE209 = new EnumModel("CH", "Switzerland (CH)");
    public static final EnumModel VALUE210 = new EnumModel("SE", "Syrian Arab Republic (SE)");
    public static final EnumModel VALUE211 = new EnumModel("TW", "Taiwan (Province of China) (TW)");
    public static final EnumModel VALUE212 = new EnumModel("TJ", "Tajikistan (TJ)");
    public static final EnumModel VALUE213 = new EnumModel("TZ", "Tanzania, United Republic Of (TZ)");
    public static final EnumModel VALUE214 = new EnumModel("TH", "Thailand (TH)");
    public static final EnumModel VALUE215 = new EnumModel("TL", "Timor-leste (TL)");
    public static final EnumModel VALUE216 = new EnumModel("TG", "Togo (TG)");
    public static final EnumModel VALUE217 = new EnumModel("TK", "Tokelau (TK)");
    public static final EnumModel VALUE218 = new EnumModel("TO", "Tonga (TO)");
    public static final EnumModel VALUE219 = new EnumModel("TT", "Trinidad And Tobago (TT)");
    public static final EnumModel VALUE220 = new EnumModel("TN", "Tunisia (TN)");
    public static final EnumModel VALUE221 = new EnumModel("TR", "Turkey (TR)");
    public static final EnumModel VALUE222 = new EnumModel("TM", "Turkmenistan (TM)");
    public static final EnumModel VALUE223 = new EnumModel("TC", "Turks And Caicos Islands (TC)");
    public static final EnumModel VALUE224 = new EnumModel("TV", "Tuvalu (TV)");
    public static final EnumModel VALUE225 = new EnumModel("UG", "Uganda (UG)");
    public static final EnumModel VALUE226 = new EnumModel("UA", "Ukraine (UA)");
    public static final EnumModel VALUE227 = new EnumModel("AE", "United Arab Emirates (AE)");
    public static final EnumModel VALUE228 = new EnumModel("UK", "United Kingdom ");
    public static final EnumModel VALUE229 = new EnumModel("UY", "Uruguay (UY)");
    public static final EnumModel VALUE230 = new EnumModel("UZ", "Uzbekistan (UZ)");
    public static final EnumModel VALUE231 = new EnumModel("VU", "Vanuatu (VU)");
    public static final EnumModel VALUE232 = new EnumModel("VE", "Venezuela, (Bolivarian Republic Of) (VE)");
    public static final EnumModel VALUE233 = new EnumModel("VN", "Viet Nam (VN)");
    public static final EnumModel VALUE234 = new EnumModel("VG", "Virgin Islands, British (VG)");
    public static final EnumModel VALUE235 = new EnumModel("WF", "Wallis And Futuna (WF)");
    public static final EnumModel VALUE236 = new EnumModel("EH", "Western Sahara (EH)");
    public static final EnumModel VALUE237 = new EnumModel("YE", "Yemen (YE)");
    public static final EnumModel VALUE238 = new EnumModel("ZM", "Zambia (ZM)");
    public static final EnumModel VALUE239 = new EnumModel("ZW", "Zimbabwe (ZW)");


    public static ArrayList<EnumModel> getForeignCountries() {
        return new ArrayList<>() {{
            add(VALUE1);
            add(VALUE2);
            add(VALUE3);
            add(VALUE4);
            add(VALUE5);
            add(VALUE6);
            add(VALUE7);
            add(VALUE8);
            add(VALUE9);
            add(VALUE10);
            add(VALUE11);
            add(VALUE12);
            add(VALUE13);
            add(VALUE14);
            add(VALUE15);
            add(VALUE16);
            add(VALUE17);
            add(VALUE18);
            add(VALUE19);
            add(VALUE20);
            add(VALUE21);
            add(VALUE22);
            add(VALUE23);
            add(VALUE24);
            add(VALUE25);
            add(VALUE26);
            add(VALUE27);
            add(VALUE28);
            add(VALUE29);
            add(VALUE30);
            add(VALUE31);
            add(VALUE32);
            add(VALUE33);
            add(VALUE34);
            add(VALUE35);
            add(VALUE36);
            add(VALUE37);
            add(VALUE38);
            add(VALUE39);
            add(VALUE40);
            add(VALUE41);
            add(VALUE42);
            add(VALUE43);
            add(VALUE44);
            add(VALUE45);
            add(VALUE46);
            add(VALUE47);
            add(VALUE48);
            add(VALUE49);
            add(VALUE50);
            add(VALUE51);
            add(VALUE52);
            add(VALUE53);
            add(VALUE54);
            add(VALUE55);
            add(VALUE56);
            add(VALUE57);
            add(VALUE58);
            add(VALUE59);
            add(VALUE60);
            add(VALUE61);
            add(VALUE62);
            add(VALUE63);
            add(VALUE64);
            add(VALUE65);
            add(VALUE66);
            add(VALUE67);
            add(VALUE68);
            add(VALUE69);
            add(VALUE70);
            add(VALUE71);
            add(VALUE72);
            add(VALUE73);
            add(VALUE74);
            add(VALUE75);
            add(VALUE76);
            add(VALUE77);
            add(VALUE78);
            add(VALUE79);
            add(VALUE80);
            add(VALUE81);
            add(VALUE82);
            add(VALUE83);
            add(VALUE84);
            add(VALUE85);
            add(VALUE86);
            add(VALUE87);
            add(VALUE88);
            add(VALUE89);
            add(VALUE90);
            add(VALUE91);
            add(VALUE92);
            add(VALUE93);
            add(VALUE94);
            add(VALUE95);
            add(VALUE96);
            add(VALUE97);
            add(VALUE98);
            add(VALUE99);
            add(VALUE100);
            add(VALUE101);
            add(VALUE102);
            add(VALUE103);
            add(VALUE104);
            add(VALUE105);
            add(VALUE106);
            add(VALUE107);
            add(VALUE108);
            add(VALUE109);
            add(VALUE110);
            add(VALUE111);
            add(VALUE112);
            add(VALUE113);
            add(VALUE114);
            add(VALUE115);
            add(VALUE116);
            add(VALUE117);
            add(VALUE118);
            add(VALUE119);
            add(VALUE120);
            add(VALUE121);
            add(VALUE122);
            add(VALUE123);
            add(VALUE124);
            add(VALUE125);
            add(VALUE126);
            add(VALUE127);
            add(VALUE128);
            add(VALUE129);
            add(VALUE130);
            add(VALUE131);
            add(VALUE132);
            add(VALUE133);
            add(VALUE134);
            add(VALUE135);
            add(VALUE136);
            add(VALUE137);
            add(VALUE138);
            add(VALUE139);
            add(VALUE140);
            add(VALUE141);
            add(VALUE142);
            add(VALUE143);
            add(VALUE144);
            add(VALUE145);
            add(VALUE146);
            add(VALUE147);
            add(VALUE148);
            add(VALUE149);
            add(VALUE150);
            add(VALUE151);
            add(VALUE152);
            add(VALUE153);
            add(VALUE154);
            add(VALUE155);
            add(VALUE156);
            add(VALUE157);
            add(VALUE158);
            add(VALUE159);
            add(VALUE160);
            add(VALUE161);
            add(VALUE162);
            add(VALUE163);
            add(VALUE164);
            add(VALUE165);
            add(VALUE166);
            add(VALUE167);
            add(VALUE168);
            add(VALUE169);
            add(VALUE170);
            add(VALUE171);
            add(VALUE172);
            add(VALUE173);
            add(VALUE174);
            add(VALUE175);
            add(VALUE176);
            add(VALUE177);
            add(VALUE178);
            add(VALUE179);
            add(VALUE180);
            add(VALUE181);
            add(VALUE182);
            add(VALUE183);
            add(VALUE184);
            add(VALUE185);
            add(VALUE186);
            add(VALUE187);
            add(VALUE188);
            add(VALUE189);
            add(VALUE190);
            add(VALUE191);
            add(VALUE192);
            add(VALUE193);
            add(VALUE194);
            add(VALUE195);
            add(VALUE196);
            add(VALUE197);
            add(VALUE198);
            add(VALUE199);
            add(VALUE200);
            add(VALUE201);
            add(VALUE202);
            add(VALUE203);
            add(VALUE204);
            add(VALUE205);
            add(VALUE206);
            add(VALUE207);
            add(VALUE208);
            add(VALUE209);
            add(VALUE210);
            add(VALUE211);
            add(VALUE212);
            add(VALUE213);
            add(VALUE214);
            add(VALUE215);
            add(VALUE216);
            add(VALUE217);
            add(VALUE218);
            add(VALUE219);
            add(VALUE220);
            add(VALUE221);
            add(VALUE222);
            add(VALUE223);
            add(VALUE224);
            add(VALUE225);
            add(VALUE226);
            add(VALUE227);
            add(VALUE228);
            add(VALUE229);
            add(VALUE230);
            add(VALUE231);
            add(VALUE232);
            add(VALUE233);
            add(VALUE234);
            add(VALUE235);
            add(VALUE236);
            add(VALUE237);
            add(VALUE238);
            add(VALUE239);
        }};
    }

}
