package com.boir.sdk.enums;

import com.boir.sdk.enums.model.EnumModel;

import java.util.ArrayList;

public class StateEnum {

    public static final EnumModel AL = new EnumModel("AL", "Alabama");
    public static final EnumModel AK = new EnumModel("AK", "Alaska");
    public static final EnumModel AZ = new EnumModel("AZ", "Arizona");
    public static final EnumModel AR = new EnumModel("AR", "Arkansas");
    public static final EnumModel CA = new EnumModel("CA", "California");
    public static final EnumModel CO = new EnumModel("CO", "Colorado");
    public static final EnumModel CT = new EnumModel("CT", "Connecticut");
    public static final EnumModel DE = new EnumModel("DE", "Delaware");
    public static final EnumModel DC = new EnumModel("DC", "DistrictofColumbia");
    public static final EnumModel FL = new EnumModel("FL", "Florida");
    public static final EnumModel GA = new EnumModel("GA", "Georgia");
    public static final EnumModel HI = new EnumModel("HI", "Hawaii");
    public static final EnumModel ID = new EnumModel("ID", "Idaho");
    public static final EnumModel IL = new EnumModel("IL", "Illinois");
    public static final EnumModel IN = new EnumModel("IN", "Indiana");
    public static final EnumModel IA = new EnumModel("IA", "Iowa");
    public static final EnumModel KS = new EnumModel("KS", "Kansas");
    public static final EnumModel KY = new EnumModel("KY", "Kentucky");
    public static final EnumModel LA = new EnumModel("LA", "Louisiana");
    public static final EnumModel ME = new EnumModel("ME", "Maine");
    public static final EnumModel MD = new EnumModel("MD", "MaryLand");
    public static final EnumModel MA = new EnumModel("MA", "Massachusetts");
    public static final EnumModel MI = new EnumModel("MI", "Michigan");
    public static final EnumModel MN = new EnumModel("MN", "Minnesota");
    public static final EnumModel MS = new EnumModel("MS", "Mississippi");
    public static final EnumModel MO = new EnumModel("MO", "Missouri");
    public static final EnumModel MT = new EnumModel("MT", "Montana");
    public static final EnumModel NE = new EnumModel("NE", "Nebraska");
    public static final EnumModel NV = new EnumModel("NV", "Nevada");
    public static final EnumModel NH = new EnumModel("NH", "NewHampshire");
    public static final EnumModel NJ = new EnumModel("NJ", "NewJersey");
    public static final EnumModel NM = new EnumModel("NM", "NewMexico");
    public static final EnumModel NY = new EnumModel("NY", "NewYork");
    public static final EnumModel NC = new EnumModel("NC", "NorthCarolina");
    public static final EnumModel ND = new EnumModel("ND", "NorthDakota");
    public static final EnumModel OH = new EnumModel("OH", "Ohio");
    public static final EnumModel OK = new EnumModel("OK", "Oklahoma");
    public static final EnumModel OR = new EnumModel("OR", "Oregon");
    public static final EnumModel PA = new EnumModel("PA", "Pennsylvania");
    public static final EnumModel RI = new EnumModel("Name", "RhodeIsland");
    public static final EnumModel SC = new EnumModel("SC", "SouthCarolina");
    public static final EnumModel SD = new EnumModel("SD", "SouthDakota");
    public static final EnumModel TN = new EnumModel("TN", "Tennessee");
    public static final EnumModel TX = new EnumModel("TX", "Texas");
    public static final EnumModel UT = new EnumModel("UT", "Utah");
    public static final EnumModel VT = new EnumModel("VT", "Vermont");
    public static final EnumModel VA = new EnumModel("VA", "Virginia");
    public static final EnumModel WA = new EnumModel("WA", "Washington");
    public static final EnumModel WV = new EnumModel("WV", "WestVirginia");
    public static final EnumModel WI = new EnumModel("WI", "Wisconsin");
    public static final EnumModel WY = new EnumModel("WY", "Wyoming");
    public static final EnumModel AS = new EnumModel("AS", "AmericanSamoa");
    public static final EnumModel FM = new EnumModel("FM", "FederatedStatesofMicronesia");
    public static final EnumModel GU = new EnumModel("GU", "Guam");
    public static final EnumModel MH = new EnumModel("MH", "MarshallIslands");
    public static final EnumModel MP = new EnumModel("MP", "NorthernMarianaIslands");
    public static final EnumModel PW = new EnumModel("PW", "Palau");
    public static final EnumModel PR = new EnumModel("PR", "PuertoRico");
    public static final EnumModel VI = new EnumModel("VI", "VirginIslands");
    public static final EnumModel AA = new EnumModel("AA", "ArmedForcesAmericas");
    public static final EnumModel AE = new EnumModel("AE", "ArmedForcesEurope");
    public static final EnumModel AP = new EnumModel("AP", "ArmedForcesPacific");

    public static ArrayList<EnumModel> getStates() {
        return new ArrayList<>() {{
            add(AL);
            add(AK);
            add(AZ);
            add(AR);
            add(CA);
            add(CO);
            add(CT);
            add(DE);
            add(DC);
            add(FL);
            add(GA);
            add(HI);
            add(ID);
            add(IL);
            add(IN);
            add(IA);
            add(KS);
            add(KY);
            add(LA);
            add(ME);
            add(MD);
            add(MA);
            add(MI);
            add(MN);
            add(MS);
            add(MO);
            add(MT);
            add(NE);
            add(NV);
            add(NH);
            add(NJ);
            add(NM);
            add(NY);
            add(NC);
            add(ND);
            add(OH);
            add(OK);
            add(OR);
            add(PA);
            add(RI);
            add(SC);
            add(SD);
            add(TN);
            add(TX);
            add(UT);
            add(VT);
            add(VA);
            add(WA);
            add(WV);
            add(WI);
            add(WY);
            add(AS);
            add(FM);
            add(GU);
            add(MH);
            add(MP);
            add(PW);
            add(PR);
            add(VI);
            add(AA);
            add(AE);
            add(AP);
        }};
    }

    public static final EnumModel value1 = new EnumModel("AGU", "Aguascalientes (AGU)");
    public static final EnumModel value2 = new EnumModel("BCN", "Baja California (BCN)");
    public static final EnumModel value3 = new EnumModel("BCS", "Baja California Sur (BCS)");
    public static final EnumModel value4 = new EnumModel("CAM", "Campeche (CAM)");
    public static final EnumModel value5 = new EnumModel("CHP", "Chiapas (CHP)");
    public static final EnumModel value6 = new EnumModel("CHH", "Chihuahua (CHH)");
    public static final EnumModel value7 = new EnumModel("COA", "Coahuila (COA)");
    public static final EnumModel value8 = new EnumModel("COL", "Colima (COL)");
    public static final EnumModel value9 = new EnumModel("CMX", "Mexican Federal District (CMX)");
    public static final EnumModel value10 = new EnumModel("DUR", "Durango (DUR)");
    public static final EnumModel value11 = new EnumModel("GUA", "Guanajuato (GUA)");
    public static final EnumModel value12 = new EnumModel("GRO", "Guerrero (GRO)");
    public static final EnumModel value13 = new EnumModel("HID", "Hidalgo (HID)");
    public static final EnumModel value14 = new EnumModel("JAL", "Jalisco (JAL)");
    public static final EnumModel value15 = new EnumModel("MEX", "México (MEX)");
    public static final EnumModel value16 = new EnumModel("MIC", "Michoacán (MIC)");
    public static final EnumModel value17 = new EnumModel("MOR", "Morelos (MOR)");
    public static final EnumModel value18 = new EnumModel("NAY", "Nayarit (NAY)");
    public static final EnumModel value19 = new EnumModel("NLE", "Neuvo Leon (NLE)");
    public static final EnumModel value20 = new EnumModel("OAX", "Oaxaca (OAX)");
    public static final EnumModel value21 = new EnumModel("PUE", "Puebla (PUE)");
    public static final EnumModel value22 = new EnumModel("QUE", "Querétaro (QUE)");
    public static final EnumModel value23 = new EnumModel("ROO", "Quintana Roo (ROO)");
    public static final EnumModel value24 = new EnumModel("SLP", "San Luis Potosi (SLP)");
    public static final EnumModel value25 = new EnumModel("SIN", "Sinaloa (SIN)");
    public static final EnumModel value26 = new EnumModel("SON", "Sonora (SON)");
    public static final EnumModel value27 = new EnumModel("TAB", "Tabasco (TAB)");
    public static final EnumModel value28 = new EnumModel("TAM", "Tamaulipas (TAM)");
    public static final EnumModel value29 = new EnumModel("TLA", "Tlaxcala (TLA)");
    public static final EnumModel value30 = new EnumModel("VER", "Veracruz (VER)");
    public static final EnumModel value31 = new EnumModel("YUC", "Yucatan (YUC)");
    public static final EnumModel value32 = new EnumModel("ZAC", "Zacatecas (ZAC)");

    public static ArrayList<EnumModel> getMexicoStates() {
        return new ArrayList<>() {{
            add(value1);
            add(value2);
            add(value3);
            add(value4);
            add(value5);
            add(value6);
            add(value7);
            add(value8);
            add(value9);
            add(value10);
            add(value11);
            add(value12);
            add(value13);
            add(value14);
            add(value15);
            add(value16);
            add(value17);
            add(value18);
            add(value19);
            add(value20);
            add(value21);
            add(value22);
            add(value23);
            add(value24);
            add(value25);
            add(value26);
            add(value27);
            add(value28);
            add(value29);
            add(value30);
            add(value31);
            add(value32);
        }};
    }

    public static final EnumModel VALUE1 = new EnumModel("AB", "Alberta (AB)");
    public static final EnumModel VALUE2 = new EnumModel("BC", "British Columbia (BC)");
    public static final EnumModel VALUE3 = new EnumModel("MB", "Manitoba (MB)");
    public static final EnumModel VALUE4 = new EnumModel("NB", "New Brunswick (NB)");
    public static final EnumModel VALUE5 = new EnumModel("NL", "Newfoundland and Labrador (NL)");
    public static final EnumModel VALUE6 = new EnumModel("NT", "Northwest Territory (NT)");
    public static final EnumModel VALUE7 = new EnumModel("NS", "Nova Scotia (NS)");
    public static final EnumModel VALUE8 = new EnumModel("NU", "Nunavut (NU)");
    public static final EnumModel VALUE9 = new EnumModel("ON", "Ontario (ON)");
    public static final EnumModel VALUE10 = new EnumModel("PE", "Prince Edward Island (PE)");
    public static final EnumModel VALUE11 = new EnumModel("QC", "Quebec (QC)");
    public static final EnumModel VALUE12 = new EnumModel("SK", "Saskatchewan (SK)");
    public static final EnumModel VALUE13 = new EnumModel("YT", "Yukon Territory (YT)");

    public static ArrayList<EnumModel> getCanadaStates() {
        return new ArrayList<>() {{
            add(VALUE1);
            add(VALUE2);
            add(VALUE3);
            add(VALUE4);
            add(VALUE5);
            add(VALUE6);
            add(VALUE7);
            add(VALUE8);
            add(VALUE9);
            add(VALUE10);
            add(VALUE11);
            add(VALUE12);
            add(VALUE13);
        }};
    }

}