package com.formw2.sdk.enums;

import com.formw2.sdk.enums.model.EnumModel;

import java.util.ArrayList;

public class CountyNameEnum {

    public static final EnumModel ADAMS = new EnumModel("Adams", "Adams");
    public static final EnumModel ALLEN = new EnumModel("Allen", "Allen");
    public static final EnumModel BARTHOLOMEW = new EnumModel("Bartholomew", "Bartholomew");
    public static final EnumModel BENTON = new EnumModel("Benton", "Benton");
    public static final EnumModel BLACKFORD = new EnumModel("Blackford", "Blackford");
    public static final EnumModel BOONE = new EnumModel("Boone", "Boone");
    public static final EnumModel BROWN = new EnumModel("Brown", "Brown");
    public static final EnumModel CARROL = new EnumModel("Carrol", "Carrol");
    public static final EnumModel CASS = new EnumModel("Cass", "Cass");
    public static final EnumModel CLARK = new EnumModel("Clark", "Clark");
    public static final EnumModel CLAY = new EnumModel("Clay", "Clay");
    public static final EnumModel CLINTON = new EnumModel("Clinton", "Clinton");
    public static final EnumModel CRAWFORD = new EnumModel("Crawford", "Crawford");
    public static final EnumModel DAVIESS = new EnumModel("Daviess", "Daviess");
    public static final EnumModel DEARBORN = new EnumModel("Dearborn", "Dearborn");
    public static final EnumModel DECATUR = new EnumModel("Decatur", "Decatur");
    public static final EnumModel DEKALB = new EnumModel("DeKalb", "DeKalb");
    public static final EnumModel DELAWARE = new EnumModel("Delaware", "Delaware");
    public static final EnumModel DUBOIS = new EnumModel("Dubois", "Dubois");
    public static final EnumModel ELKHART = new EnumModel("Elkhart", "Elkhart");
    public static final EnumModel FAYETTE = new EnumModel("Fayette", "Fayette");
    public static final EnumModel FLOYD = new EnumModel("Floyd", "Floyd");
    public static final EnumModel FOUNTAIN = new EnumModel("Fountain", "Fountain");
    public static final EnumModel FRANKLIN = new EnumModel("Franklin", "Franklin");
    public static final EnumModel FULTON = new EnumModel("Fulton", "Fulton");
    public static final EnumModel GIBSON = new EnumModel("Gibson", "Gibson");
    public static final EnumModel GRANT = new EnumModel("Grant", "Grant");
    public static final EnumModel GREENE = new EnumModel("Greene", "Greene");
    public static final EnumModel HAMILTON = new EnumModel("Hamilton", "Hamilton");
    public static final EnumModel HANCOCK = new EnumModel("Hancock", "Hancock");
    public static final EnumModel HARRISON = new EnumModel("Harrison", "Harrison");
    public static final EnumModel HENDRICKS = new EnumModel("Hendricks", "Hendricks");
    public static final EnumModel HENRY = new EnumModel("Henry", "Henry");
    public static final EnumModel HOWARD = new EnumModel("Howard", "Howard");
    public static final EnumModel HUNTINGTON = new EnumModel("Huntington", "Huntington");
    public static final EnumModel JACKSON = new EnumModel("Jackson", "Jackson");
    public static final EnumModel JASPER = new EnumModel("Jasper", "Jasper");
    public static final EnumModel JAY = new EnumModel("Jay", "Jay");
    public static final EnumModel JEFFERSON = new EnumModel("Jefferson", "Jefferson");
    public static final EnumModel JENNINGS = new EnumModel("Jennings", "Jennings");
    public static final EnumModel JOHNSON = new EnumModel("Johnson", "Johnson");
    public static final EnumModel KNOX = new EnumModel("Knox", "Knox");
    public static final EnumModel KOSCIUSKO = new EnumModel("Kosciusko", "Kosciusko");
    public static final EnumModel LAGRANGE = new EnumModel("LaGrange", "LaGrange");
    public static final EnumModel LAKE = new EnumModel("Lake", "Lake");
    public static final EnumModel LAPORTE = new EnumModel("LaPorte", "LaPorte");
    public static final EnumModel LAWRENCE = new EnumModel("Lawrence", "Lawrence");
    public static final EnumModel MADISON = new EnumModel("Madison", "Madison");
    public static final EnumModel MARION = new EnumModel("Marion", "Marion");
    public static final EnumModel MARSHALL = new EnumModel("Marshall", "Marshall");
    public static final EnumModel MARTIN = new EnumModel("Martin", "Martin");
    public static final EnumModel MIAMI = new EnumModel("Miami", "Miami");
    public static final EnumModel MONROE = new EnumModel("Monroe", "Monroe");
    public static final EnumModel MONTGOMERY = new EnumModel("Montgomery", "Montgomery");
    public static final EnumModel MORGAN = new EnumModel("Morgan", "Morgan");
    public static final EnumModel NEWTON = new EnumModel("Newton", "Newton");
    public static final EnumModel NOBLE = new EnumModel("Noble", "Noble");
    public static final EnumModel OHIO = new EnumModel("Ohio", "Ohio");
    public static final EnumModel ORANGE = new EnumModel("Orange", "Orange");
    public static final EnumModel OWEN = new EnumModel("Owen", "Owen");
    public static final EnumModel PARKE = new EnumModel("Parke", "Parke");
    public static final EnumModel PERRY = new EnumModel("Perry", "Perry");
    public static final EnumModel PIKE = new EnumModel("Pike", "Pike");
    public static final EnumModel PORTER = new EnumModel("Porter", "Porter");
    public static final EnumModel POSEY = new EnumModel("Posey", "Posey");
    public static final EnumModel PULASKI = new EnumModel("Pulaski", "Pulaski");
    public static final EnumModel PUTNAM = new EnumModel("Putnam", "Putnam");
    public static final EnumModel RANDOLPH = new EnumModel("Randolph", "Randolph");
    public static final EnumModel RIPLEY = new EnumModel("Ripley", "Ripley");
    public static final EnumModel RUSH = new EnumModel("Rush", "Rush");
    public static final EnumModel ST_JOSEPH = new EnumModel("St.Joseph", "St.Joseph");
    public static final EnumModel SCOTT = new EnumModel("Scott", "Scott");
    public static final EnumModel SHELBY = new EnumModel("Shelby", "Shelby");
    public static final EnumModel SPENCER = new EnumModel("Spencer", "Spencer");
    public static final EnumModel STARKE = new EnumModel("Starke", "Starke");
    public static final EnumModel STEUBEN = new EnumModel("Steuben", "Steuben");
    public static final EnumModel SULLIVAN = new EnumModel("Sullivan", "Sullivan");
    public static final EnumModel SWITZERLAND = new EnumModel("Switzerland", "Switzerland");
    public static final EnumModel TIPPECANOE = new EnumModel("Tippecanoe", "Tippecanoe");
    public static final EnumModel TIPTON = new EnumModel("Tipton", "Tipton");
    public static final EnumModel UNION = new EnumModel("Union", "Union");
    public static final EnumModel VANDERBURGH = new EnumModel("Vanderburgh", "Vanderburgh");
    public static final EnumModel VERMILLION = new EnumModel("Vermillion", "Vermillion");
    public static final EnumModel VIGO = new EnumModel("Vigo", "Vigo");
    public static final EnumModel WABASH = new EnumModel("Wabash", "Wabash");
    public static final EnumModel WARREN = new EnumModel("Warren", "Warren");
    public static final EnumModel WARRICK = new EnumModel("Warrick", "Warrick");
    public static final EnumModel WASHINGTON = new EnumModel("Washington", "Washington");
    public static final EnumModel WAYNE = new EnumModel("Wayne", "Wayne");
    public static final EnumModel WELLS = new EnumModel("Wells", "Wells");
    public static final EnumModel WHITE = new EnumModel("White", "White");
    public static final EnumModel WHITLEY = new EnumModel("Whitley", "Whitley");

    public static ArrayList<EnumModel> getCountyNames() {
        return new ArrayList<>() {
            {
                add(ADAMS);
                add(ALLEN);
                add(BARTHOLOMEW);
                add(BENTON);
                add(BLACKFORD);
                add(BOONE);
                add(BROWN);
                add(CARROL);
                add(CASS);
                add(CLARK);
                add(CLAY);
                add(CLINTON);
                add(CRAWFORD);
                add(DAVIESS);
                add(DEARBORN);
                add(DECATUR);
                add(DEKALB);
                add(DELAWARE);
                add(DUBOIS);
                add(ELKHART);
                add(FAYETTE);
                add(FLOYD);
                add(FOUNTAIN);
                add(FRANKLIN);
                add(FULTON);
                add(GIBSON);
                add(GRANT);
                add(GREENE);
                add(HAMILTON);
                add(HANCOCK);
                add(HARRISON);
                add(HENDRICKS);
                add(HENRY);
                add(HOWARD);
                add(HUNTINGTON);
                add(JACKSON);
                add(JASPER);
                add(JAY);
                add(JEFFERSON);
                add(JENNINGS);
                add(JOHNSON);
                add(KNOX);
                add(KOSCIUSKO);
                add(LAGRANGE);
                add(LAKE);
                add(LAPORTE);
                add(LAWRENCE);
                add(MADISON);
                add(MARION);
                add(MARSHALL);
                add(MARTIN);
                add(MIAMI);
                add(MONROE);
                add(MONTGOMERY);
                add(MORGAN);
                add(NEWTON);
                add(NOBLE);
                add(OHIO);
                add(ORANGE);
                add(OWEN);
                add(PARKE);
                add(PERRY);
                add(PIKE);
                add(PORTER);
                add(POSEY);
                add(PULASKI);
                add(PUTNAM);
                add(RANDOLPH);
                add(RIPLEY);
                add(RUSH);
                add(ST_JOSEPH);
                add(SCOTT);
                add(SHELBY);
                add(SPENCER);
                add(STARKE);
                add(STEUBEN);
                add(SULLIVAN);
                add(SWITZERLAND);
                add(TIPPECANOE);
                add(TIPTON);
                add(UNION);
                add(VANDERBURGH);
                add(VERMILLION);
                add(VIGO);
                add(WABASH);
                add(WARREN);
                add(WARRICK);
                add(WASHINGTON);
                add(WAYNE);
                add(WELLS);
                add(WHITE);
                add(WHITLEY);
            }
        };
    }

}
