package com.form1099NEC.sdk.enums;

import com.form1099NEC.sdk.enums.model.EnumModel;

import java.util.ArrayList;

public class CountryEnum {
    public static final EnumModel CA = new EnumModel("CA", "Canada");
    public static final EnumModel MX = new EnumModel("MX", "Mexico");
    public static final EnumModel AF = new EnumModel("AF", "Afghanistan");
    public static final EnumModel AX = new EnumModel("AX", "Akrotiri");
    public static final EnumModel XI = new EnumModel("XI", "Aland Island");
    public static final EnumModel AL = new EnumModel("AL", "Albania");
    public static final EnumModel AG = new EnumModel("AG", "Algeria");
    public static final EnumModel AQ = new EnumModel("AQ", "American Samoa");
    public static final EnumModel AN = new EnumModel("AN", "Andorra");
    public static final EnumModel AO = new EnumModel("AO", "Angola");
    public static final EnumModel AV = new EnumModel("AV", "Anguilla");
    public static final EnumModel AY = new EnumModel("AY", "Antarctica");
    public static final EnumModel AC = new EnumModel("AC", "Antigua and Barbuda");
    public static final EnumModel AR = new EnumModel("AR", "Argentina");
    public static final EnumModel AM = new EnumModel("AM", "Armenia");
    public static final EnumModel AA = new EnumModel("AA", "Aruba");
    public static final EnumModel XA = new EnumModel("XA", "Ascension");
    public static final EnumModel AT = new EnumModel("AT", "Ashmore and Cartier Islands");
    public static final EnumModel AS = new EnumModel("AS", "Australia");
    public static final EnumModel AU = new EnumModel("AU", "Austria");
    public static final EnumModel AJ = new EnumModel("AJ", "Azerbaijan");
    public static final EnumModel XZ = new EnumModel("XZ", "Azores");
    public static final EnumModel BF = new EnumModel("BF", "Bahamas");
    public static final EnumModel BA = new EnumModel("BA", "Bahrain");
    public static final EnumModel FQ = new EnumModel("FQ", "Baker Islands");
    public static final EnumModel BG = new EnumModel("BG", "Bangladesh");
    public static final EnumModel BB = new EnumModel("BB", "Barbados");
    public static final EnumModel BS = new EnumModel("BS", "Bassas da India");
    public static final EnumModel BO = new EnumModel("BO", "Belarus");
    public static final EnumModel BE = new EnumModel("BE", "Belgium");
    public static final EnumModel BH = new EnumModel("BH", "Belize");
    public static final EnumModel BN = new EnumModel("BN", "Benin");
    public static final EnumModel BD = new EnumModel("BD", "Bermuda");
    public static final EnumModel BT = new EnumModel("BT", "Bhutan");
    public static final EnumModel BL = new EnumModel("BL", "Bolivia");
    public static final EnumModel BK = new EnumModel("BK", "Bosnia-Herzegovina");
    public static final EnumModel BC = new EnumModel("BC", "Botswana");
    public static final EnumModel BV = new EnumModel("BV", "Bouvet Island");
    public static final EnumModel BR = new EnumModel("BR", "Brazil");
    public static final EnumModel IO = new EnumModel("IO", "British Indian OceanTerritory");
    public static final EnumModel VI = new EnumModel("VI", "British Virgin Islands");
    public static final EnumModel BX = new EnumModel("BX", "Brunei");
    public static final EnumModel BU = new EnumModel("BU", "Bulgaria");
    public static final EnumModel UV = new EnumModel("UV", "Burkina Faso");
    public static final EnumModel BM = new EnumModel("BM", "Burma");
    public static final EnumModel BY = new EnumModel("BY", "Burundi");
    public static final EnumModel CB = new EnumModel("CB", "Cambodia");
    public static final EnumModel CM = new EnumModel("CM", "Cameroon");
    public static final EnumModel XY = new EnumModel("XY", "Canary Islands");
    public static final EnumModel CV = new EnumModel("CV", "Cape Verde");
    public static final EnumModel CJ = new EnumModel("CJ", "Cayman Islands");
    public static final EnumModel CT = new EnumModel("CT", "Central African Republic");
    public static final EnumModel CD = new EnumModel("CD", "Chad");
    public static final EnumModel XC = new EnumModel("XC", "Channel Islands");
    public static final EnumModel CI = new EnumModel("CI", "Chile");
    public static final EnumModel CH = new EnumModel("CH", "China");
    public static final EnumModel KT = new EnumModel("KT", "Christmas Island");
    public static final EnumModel IP = new EnumModel("IP", "Clipperton Island");
    public static final EnumModel CK = new EnumModel("CK", "Cocos (Keeling); Islands");
    public static final EnumModel CO = new EnumModel("CO", "Colombia");
    public static final EnumModel CN = new EnumModel("CN", "Comoros");
    public static final EnumModel CF = new EnumModel("CF", "Congo (Brazzaville);");
    public static final EnumModel CG = new EnumModel("CG", "Congo (Kinshasa);");
    public static final EnumModel CW = new EnumModel("CW", "Cook Islands");
    public static final EnumModel CR = new EnumModel("CR", "Coral Sea Islands");
    public static final EnumModel VP = new EnumModel("VP", "Corsica");
    public static final EnumModel CS = new EnumModel("CS", "Costa Rica");
    public static final EnumModel IV = new EnumModel("IV", "Cote D'Ivoire (IvoryCoast);");
    public static final EnumModel HR = new EnumModel("HR", "Croatia");
    public static final EnumModel CU = new EnumModel("CU", "Cuba");
    public static final EnumModel CY = new EnumModel("CY", "Cyprus");
    public static final EnumModel EZ = new EnumModel("EZ", "Czech Republic");
    public static final EnumModel DA = new EnumModel("DA", "Denmark");
    public static final EnumModel DX = new EnumModel("DX", "Dhekelia");
    public static final EnumModel DJ = new EnumModel("DJ", "Djibouti");
    public static final EnumModel DO = new EnumModel("DO", "Dominica");
    public static final EnumModel DR = new EnumModel("DR", "Dominican Republic");
    public static final EnumModel TT = new EnumModel("TT", "East Timor");
    public static final EnumModel EC = new EnumModel("EC", "Ecuador");
    public static final EnumModel EG = new EnumModel("EG", "Egypt");
    public static final EnumModel ES = new EnumModel("ES", "El Salvador");
    public static final EnumModel UK = new EnumModel("UK", "England");
    public static final EnumModel EK = new EnumModel("EK", "Equatorial Guinea");
    public static final EnumModel ER = new EnumModel("ER", "Eritrea");
    public static final EnumModel EN = new EnumModel("EN", "Estonia");
    public static final EnumModel ET = new EnumModel("ET", "Ethiopia");
    public static final EnumModel EU = new EnumModel("EU", "Europa Island");
    public static final EnumModel FK = new EnumModel("FK", "Falkland Islands (Islas Malvinas);");
    public static final EnumModel FO = new EnumModel("FO", "Faroe Islands");
    public static final EnumModel FM = new EnumModel("FM", "Federated States of Micronesia");
    public static final EnumModel FJ = new EnumModel("FJ", "Fiji");
    public static final EnumModel FI = new EnumModel("FI", "Finland");
    public static final EnumModel FR = new EnumModel("FR", "France");
    public static final EnumModel FG = new EnumModel("FG", "French Guiana");
    public static final EnumModel FP = new EnumModel("FP", "French Polynesia");
    public static final EnumModel FS = new EnumModel("FS", "French Southern and Antarctic Lands");
    public static final EnumModel GB = new EnumModel("GB", "Gabon");
    public static final EnumModel GA = new EnumModel("GA", "The Gambia");
    public static final EnumModel GZ = new EnumModel("GZ", "Gaza Strip");
    public static final EnumModel GG = new EnumModel("GG", "Georgia");
    public static final EnumModel GM = new EnumModel("GM", "Germany");
    public static final EnumModel GH = new EnumModel("GH", "Ghana");
    public static final EnumModel GI = new EnumModel("GI", "Gibraltar");
    public static final EnumModel GO = new EnumModel("GO", "Glorioso Islands");
    public static final EnumModel GR = new EnumModel("GR", "Greece");
    public static final EnumModel GL = new EnumModel("GL", "Greenland");
    public static final EnumModel GJ = new EnumModel("GJ", "Grenada");
    public static final EnumModel GP = new EnumModel("GP", "Guadeloupe");
    public static final EnumModel GQ = new EnumModel("GQ", "Guam");
    public static final EnumModel GT = new EnumModel("GT", "Guatemala");
    public static final EnumModel GK = new EnumModel("GK", "Guernsey");
    public static final EnumModel GV = new EnumModel("GV", "Guinea");
    public static final EnumModel PU = new EnumModel("PU", "Guinea-Bissau");
    public static final EnumModel GY = new EnumModel("GY", "Guyana");
    public static final EnumModel HA = new EnumModel("HA", "Haiti");
    public static final EnumModel HM = new EnumModel("HM", "Heard Island and McDonald Islands");
    public static final EnumModel HO = new EnumModel("HO", "Honduras");
    public static final EnumModel HK = new EnumModel("HK", "Hong Kong");
    public static final EnumModel HQ = new EnumModel("HQ", "Howland Island");
    public static final EnumModel HU = new EnumModel("HU", "Hungary");
    public static final EnumModel IC = new EnumModel("IC", "Iceland");
    public static final EnumModel IN = new EnumModel("IN", "India");
    public static final EnumModel ID = new EnumModel("ID", "Indonesia");
    public static final EnumModel IR = new EnumModel("IR", "Iran");
    public static final EnumModel IZ = new EnumModel("IZ", "Iraq");
    public static final EnumModel EI = new EnumModel("EI", "Ireland");
    public static final EnumModel IS = new EnumModel("IS", "Israel");
    public static final EnumModel IT = new EnumModel("IT", "Italy");
    public static final EnumModel JM = new EnumModel("JM", "Jamaica");
    public static final EnumModel JN = new EnumModel("JN", "Jan Mayen");
    public static final EnumModel JA = new EnumModel("JA", "Japan");
    public static final EnumModel DQ = new EnumModel("DQ", "Jarvis Island");
    public static final EnumModel JE = new EnumModel("JE", "Jersey");
    public static final EnumModel JQ = new EnumModel("JQ", "Johnston Atoll");
    public static final EnumModel JO = new EnumModel("JO", "Jordan");
    public static final EnumModel JU = new EnumModel("JU", "Juan de Nova Island");
    public static final EnumModel KZ = new EnumModel("KZ", "Kazakhstan");
    public static final EnumModel KE = new EnumModel("KE", "Kenya");
    public static final EnumModel KQ = new EnumModel("KQ", "Kingman Reef");
    public static final EnumModel KR = new EnumModel("KR", "Kiribati");
    public static final EnumModel KN = new EnumModel("KN", "Korea, Democratic People's Republic of (North);");
    public static final EnumModel KS = new EnumModel("KS", "Korea, Republic of (South);");
    public static final EnumModel KU = new EnumModel("KU", "Kuwait");
    public static final EnumModel KG = new EnumModel("KG", "Kyrgyzstan");
    public static final EnumModel LA = new EnumModel("LA", "Laos");
    public static final EnumModel LG = new EnumModel("LG", "Latvia");
    public static final EnumModel LE = new EnumModel("LE", "Lebanon");
    public static final EnumModel LT = new EnumModel("LT", "Lesotho");
    public static final EnumModel LI = new EnumModel("LI", "Liberia");
    public static final EnumModel LY = new EnumModel("LY", "Libya");
    public static final EnumModel LS = new EnumModel("LS", "Liechtenstein");
    public static final EnumModel LH = new EnumModel("LH", "Lithuania");
    public static final EnumModel LU = new EnumModel("LU", "Luxembourg");
    public static final EnumModel MC = new EnumModel("MC", "Macau");
    public static final EnumModel MK = new EnumModel("MK", "Macedonia");
    public static final EnumModel MA = new EnumModel("MA", "Madagascar");
    public static final EnumModel MI = new EnumModel("MI", "Malawi");
    public static final EnumModel MY = new EnumModel("MY", "Malaysia");
    public static final EnumModel MV = new EnumModel("MV", "Maldives");
    public static final EnumModel ML = new EnumModel("ML", "Mali");
    public static final EnumModel MT = new EnumModel("MT", "Malta");
    public static final EnumModel IM = new EnumModel("IM", "Man, Isle of");
    public static final EnumModel RM = new EnumModel("RM", "Marshall Islands");
    public static final EnumModel MB = new EnumModel("MB", "Martinique");
    public static final EnumModel MR = new EnumModel("MR", "Mauritania");
    public static final EnumModel MP = new EnumModel("MP", "Mauritius");
    public static final EnumModel MF = new EnumModel("MF", "Mayotte");
    public static final EnumModel MQ = new EnumModel("MQ", "Midway Islands");
    public static final EnumModel MD = new EnumModel("MD", "Moldova");
    public static final EnumModel MN = new EnumModel("MN", "Monaco");
    public static final EnumModel MG = new EnumModel("MG", "Mongolia");
    public static final EnumModel MJ = new EnumModel("MJ", "Montenegro");
    public static final EnumModel MH = new EnumModel("MH", "Montserrat");
    public static final EnumModel MO = new EnumModel("MO", "Morocco");
    public static final EnumModel MZ = new EnumModel("MZ", "Mozambique");
    public static final EnumModel XM = new EnumModel("XM", "Myanmar");
    public static final EnumModel WA = new EnumModel("WA", "Namibia");
    public static final EnumModel NR = new EnumModel("NR", "Nauru");
    public static final EnumModel BQ = new EnumModel("BQ", "Navassa Island");
    public static final EnumModel NP = new EnumModel("NP", "Nepal");
    public static final EnumModel NL = new EnumModel("NL", "Netherlands");
    public static final EnumModel NT = new EnumModel("NT", "Netherlands Antilles");
    public static final EnumModel NC = new EnumModel("NC", "New Caledonia");
    public static final EnumModel NZ = new EnumModel("NZ", "New Zealand");
    public static final EnumModel NU = new EnumModel("NU", "Nicaragua");
    public static final EnumModel NG = new EnumModel("NG", "Niger");
    public static final EnumModel NI = new EnumModel("NI", "Nigeria");
    public static final EnumModel NE = new EnumModel("NE", "Niue");
    public static final EnumModel NF = new EnumModel("NF", "Norfolk Island");
    public static final EnumModel XN = new EnumModel("XN", "Northern Ireland");
    public static final EnumModel CQ = new EnumModel("CQ", "Northern Mariana Islands");
    public static final EnumModel NO = new EnumModel("NO", "Norway");
    public static final EnumModel MU = new EnumModel("MU", "Oman");
    public static final EnumModel OC = new EnumModel("OC", "Other Country (country not identified elsewhere);");
    public static final EnumModel PK = new EnumModel("PK", "Pakistan");
    public static final EnumModel LQ = new EnumModel("LQ", "Palmyra Atoll");
    public static final EnumModel PS = new EnumModel("PS", "Palau");
    public static final EnumModel PM = new EnumModel("PM", "Panama");
    public static final EnumModel PP = new EnumModel("PP", "Papua-New Guinea");
    public static final EnumModel PF = new EnumModel("PF", "Paracel Islands");
    public static final EnumModel PA = new EnumModel("PA", "Paraguay");
    public static final EnumModel PE = new EnumModel("PE", "Peru");
    public static final EnumModel RP = new EnumModel("RP", "Philippines");
    public static final EnumModel PC = new EnumModel("PC", "Pitcairn Islands");
    public static final EnumModel PL = new EnumModel("PL", "Poland");
    public static final EnumModel PO = new EnumModel("PO", "Portugal");
    public static final EnumModel RQ = new EnumModel("RQ", "Puerto Rico");
    public static final EnumModel QA = new EnumModel("QA", "Qatar");
    public static final EnumModel RE = new EnumModel("RE", "Reunion");
    public static final EnumModel RO = new EnumModel("RO", "Romania");
    public static final EnumModel RS = new EnumModel("RS", "Russia");
    public static final EnumModel RW = new EnumModel("RW", "Rwanda");
    public static final EnumModel WS = new EnumModel("WS", "Samoa and Western Samoa");
    public static final EnumModel SM = new EnumModel("SM", "San Marino");
    public static final EnumModel TP = new EnumModel("TP", "Sao Tome and Principe");
    public static final EnumModel SA = new EnumModel("SA", "Saudi Arabia");
    public static final EnumModel XS = new EnumModel("XS", "Scotland");
    public static final EnumModel SG = new EnumModel("SG", "Senegal");
    public static final EnumModel RI = new EnumModel("RI", "Serbia");
    public static final EnumModel SE = new EnumModel("SE", "Seychelles");
    public static final EnumModel SL = new EnumModel("SL", "Sierra Leone");
    public static final EnumModel SN = new EnumModel("SN", "Singapore");
    public static final EnumModel XR = new EnumModel("XR", "Slovak Republic");
    public static final EnumModel LO = new EnumModel("LO", "Slovakia");
    public static final EnumModel SI = new EnumModel("SI", "Slovenia");
    public static final EnumModel BP = new EnumModel("BP", "Solomon Islands");
    public static final EnumModel SO = new EnumModel("SO", "Somalia");
    public static final EnumModel SF = new EnumModel("SF", "South Africa");
    public static final EnumModel SX = new EnumModel("SX", "South Georgia and the South Sandwich Islands");
    public static final EnumModel SP = new EnumModel("SP", "Spain");
    public static final EnumModel PG = new EnumModel("PG", "Spratly Islands");
    public static final EnumModel CE = new EnumModel("CE", "Sri Lanka");
    public static final EnumModel SH = new EnumModel("SH", "St. Helena");
    public static final EnumModel SC = new EnumModel("SC", "St. Kitts and Nevis");
    public static final EnumModel ST = new EnumModel("ST", "St. Lucia Island");
    public static final EnumModel SB = new EnumModel("SB", "St. Pierre and Miquelon");
    public static final EnumModel VC = new EnumModel("VC", "St. Vincent and the Grenadines");
    public static final EnumModel SU = new EnumModel("SU", "Sudan");
    public static final EnumModel NS = new EnumModel("NS", "Suriname");
    public static final EnumModel SV = new EnumModel("SV", "Svalbard");
    public static final EnumModel WZ = new EnumModel("WZ", "Swaziland");
    public static final EnumModel SW = new EnumModel("SW", "Sweden");
    public static final EnumModel SZ = new EnumModel("SZ", "Switzerland");
    public static final EnumModel SY = new EnumModel("SY", "Syria");
    public static final EnumModel TW = new EnumModel("TW", "Taiwan");
    public static final EnumModel TI = new EnumModel("TI", "Tajikistin");
    public static final EnumModel TZ = new EnumModel("TZ", "Tanzania");
    public static final EnumModel TH = new EnumModel("TH", "Thailand");
    public static final EnumModel TO = new EnumModel("TO", "Togo");
    public static final EnumModel TL = new EnumModel("TL", "Tokelau");
    public static final EnumModel TN = new EnumModel("TN", "Tonga");
    public static final EnumModel TD = new EnumModel("TD", "Trinidad and Tobago");
    public static final EnumModel XT = new EnumModel("XT", "Tristan Da Cunha");
    public static final EnumModel TE = new EnumModel("TE", "Tromelin Island");
    public static final EnumModel TS = new EnumModel("TS", "Tunisia");
    public static final EnumModel TU = new EnumModel("TU", "Turkey");
    public static final EnumModel TX = new EnumModel("TX", "Turkmenistan");
    public static final EnumModel TK = new EnumModel("TK", "Turks and Caicos Islands");
    public static final EnumModel TV = new EnumModel("TV", "Tuvalu");
    public static final EnumModel UG = new EnumModel("UG", "Uganda");
    public static final EnumModel UP = new EnumModel("UP", "Ukraine");
    public static final EnumModel AE = new EnumModel("AE", "United Arab Emirates");
    public static final EnumModel UY = new EnumModel("UY", "Uruguay");
    public static final EnumModel UZ = new EnumModel("UZ", "Uzbekistan");
    public static final EnumModel NH = new EnumModel("NH", "Vanuatu");
    public static final EnumModel VT = new EnumModel("VT", "Vatican City");
    public static final EnumModel VE = new EnumModel("VE", "Venezuela");
    public static final EnumModel VM = new EnumModel("VM", "Vietnam");
    public static final EnumModel VQ = new EnumModel("VQ", "Virgin Islands");
    public static final EnumModel WQ = new EnumModel("WQ", "Wake Island");
    public static final EnumModel XW = new EnumModel("XW", "Wales");
    public static final EnumModel WF = new EnumModel("WF", "Wallis and Futuna");
    public static final EnumModel WE = new EnumModel("WE", "West Bank");
    public static final EnumModel WI = new EnumModel("WI", "Western Sahara");
    public static final EnumModel YM = new EnumModel("YM", "Yemen (Aden);");
    public static final EnumModel YI = new EnumModel("YI", "Yugoslavia");
    public static final EnumModel ZA = new EnumModel("ZA", "Zambia");
    public static final EnumModel ZI = new EnumModel("ZI", "Zimbabwe");
    public static final EnumModel TB = new EnumModel("TB", "Saint Barthelemy");

    public static ArrayList<EnumModel> getCountry() {
        return new ArrayList<>() {{
            add(CA);
            add(MX);
            add(AF);
            add(AX);
            add(XI);
            add(AL);
            add(AG);
            add(AQ);
            add(AN);
            add(AO);
            add(AV);
            add(AY);
            add(AC);
            add(AR);
            add(AM);
            add(AA);
            add(XA);
            add(AT);
            add(AS);
            add(AU);
            add(AJ);
            add(XZ);
            add(BF);
            add(BA);
            add(FQ);
            add(BG);
            add(BB);
            add(BS);
            add(BO);
            add(BE);
            add(BH);
            add(BN);
            add(BD);
            add(BT);
            add(BL);
            add(BK);
            add(BC);
            add(BV);
            add(BR);
            add(IO);
            add(VI);
            add(BX);
            add(BU);
            add(UV);
            add(BM);
            add(BY);
            add(CB);
            add(CM);
            add(XY);
            add(CV);
            add(CJ);
            add(CT);
            add(CD);
            add(XC);
            add(CI);
            add(CH);
            add(KT);
            add(IP);
            add(CK);
            add(CO);
            add(CN);
            add(CF);
            add(CG);
            add(CW);
            add(CR);
            add(VP);
            add(CS);
            add(IV);
            add(HR);
            add(CU);
            add(CY);
            add(EZ);
            add(DA);
            add(DX);
            add(DJ);
            add(DO);
            add(DR);
            add(TT);
            add(EC);
            add(EG);
            add(ES);
            add(UK);
            add(EK);
            add(ER);
            add(EN);
            add(ET);
            add(EU);
            add(FK);
            add(FO);
            add(FM);
            add(FJ);
            add(FI);
            add(FR);
            add(FG);
            add(FP);
            add(FS);
            add(GB);
            add(GA);
            add(GZ);
            add(GG);
            add(GM);
            add(GH);
            add(GI);
            add(GO);
            add(GR);
            add(GL);
            add(GJ);
            add(GP);
            add(GQ);
            add(GT);
            add(GK);
            add(GV);
            add(PU);
            add(GY);
            add(HA);
            add(HM);
            add(HO);
            add(HK);
            add(HQ);
            add(HU);
            add(IC);
            add(IN);
            add(ID);
            add(IR);
            add(IZ);
            add(EI);
            add(IS);
            add(IT);
            add(JM);
            add(JN);
            add(JA);
            add(DQ);
            add(JE);
            add(JQ);
            add(JO);
            add(JU);
            add(KZ);
            add(KE);
            add(KQ);
            add(KR);
            add(KN);
            add(KS);
            add(KU);
            add(KG);
            add(LA);
            add(LG);
            add(LE);
            add(LT);
            add(LI);
            add(LY);
            add(LS);
            add(LH);
            add(LU);
            add(MC);
            add(MK);
            add(MA);
            add(MI);
            add(MY);
            add(MV);
            add(ML);
            add(MT);
            add(IM);
            add(RM);
            add(MB);
            add(MR);
            add(MP);
            add(MF);
            add(MQ);
            add(MD);
            add(MN);
            add(MG);
            add(MJ);
            add(MH);
            add(MO);
            add(MZ);
            add(XM);
            add(WA);
            add(NR);
            add(BQ);
            add(NP);
            add(NL);
            add(NT);
            add(NC);
            add(NZ);
            add(NU);
            add(NG);
            add(NI);
            add(NE);
            add(NF);
            add(XN);
            add(CQ);
            add(NO);
            add(MU);
            add(OC);
            add(PK);
            add(LQ);
            add(PS);
            add(PM);
            add(PP);
            add(PF);
            add(PA);
            add(PE);
            add(RP);
            add(PC);
            add(PL);
            add(PO);
            add(RQ);
            add(QA);
            add(RE);
            add(RO);
            add(RS);
            add(RW);
            add(WS);
            add(SM);
            add(TP);
            add(SA);
            add(XS);
            add(SG);
            add(RI);
            add(SE);
            add(SL);
            add(SN);
            add(XR);
            add(LO);
            add(SI);
            add(BP);
            add(SO);
            add(SF);
            add(SX);
            add(SP);
            add(PG);
            add(CE);
            add(SH);
            add(SC);
            add(ST);
            add(SB);
            add(VC);
            add(SU);
            add(NS);
            add(SV);
            add(TL);
            add(UG);
            add(WQ);
            add(WZ);
            add(TN);
            add(UP);
            add(XW);
            add(SW);
            add(TD);
            add(AE);
            add(WF);
            add(SZ);
            add(XT);
            add(UY);
            add(WE);
            add(SY);
            add(TE);
            add(UZ);
            add(WI);
            add(TW);
            add(TS);
            add(NH);
            add(YM);
            add(TI);
            add(TU);
            add(VT);
            add(YI);
            add(TZ);
            add(TX);
            add(VE);
            add(ZA);
            add(TH);
            add(TK);
            add(VM);
            add(ZI);
            add(TO);
            add(TV);
            add(VQ);
            add(TB);
        }};
    }

}
