package com.business.sdk.enums;

import com.business.sdk.enums.model.EnumModel;

import java.util.ArrayList;

public class StateEnum {

    public static final EnumModel AL = new EnumModel("AL", "Alabama");
    public static final EnumModel AK = new EnumModel("AK", "Alaska");
    public static final EnumModel AZ = new EnumModel("AZ", "Arizona");
    public static final EnumModel AR = new EnumModel("AR", "Arkansas");
    public static final EnumModel CA = new EnumModel("CA", "California");
    public static final EnumModel CO = new EnumModel("CO", "Colorado");
    public static final EnumModel CT = new EnumModel("CT", "Connecticut");
    public static final EnumModel DE = new EnumModel("DE", "Delaware");
    public static final EnumModel DC = new EnumModel("DC", "DistrictofColumbia");
    public static final EnumModel FL = new EnumModel("FL", "Florida");
    public static final EnumModel GA = new EnumModel("GA", "Georgia");
    public static final EnumModel HI = new EnumModel("HI", "Hawaii");
    public static final EnumModel ID = new EnumModel("ID", "Idaho");
    public static final EnumModel IL = new EnumModel("IL", "Illinois");
    public static final EnumModel IN = new EnumModel("IN", "Indiana");
    public static final EnumModel IA = new EnumModel("IA", "Iowa");
    public static final EnumModel KS = new EnumModel("KS", "Kansas");
    public static final EnumModel KY = new EnumModel("KY", "Kentucky");
    public static final EnumModel LA = new EnumModel("LA", "Louisiana");
    public static final EnumModel ME = new EnumModel("ME", "Maine");
    public static final EnumModel MD = new EnumModel("MD", "MaryLand");
    public static final EnumModel MA = new EnumModel("MA", "Massachusetts");
    public static final EnumModel MI = new EnumModel("MI", "Michigan");
    public static final EnumModel MN = new EnumModel("MN", "Minnesota");
    public static final EnumModel MS = new EnumModel("MS", "Mississippi");
    public static final EnumModel MO = new EnumModel("MO", "Missouri");
    public static final EnumModel MT = new EnumModel("MT", "Montana");
    public static final EnumModel NE = new EnumModel("NE", "Nebraska");
    public static final EnumModel NV = new EnumModel("NV", "Nevada");
    public static final EnumModel NH = new EnumModel("NH", "NewHampshire");
    public static final EnumModel NJ = new EnumModel("NJ", "NewJersey");
    public static final EnumModel NM = new EnumModel("NM", "NewMexico");
    public static final EnumModel NY = new EnumModel("NY", "NewYork");
    public static final EnumModel NC = new EnumModel("NC", "NorthCarolina");
    public static final EnumModel ND = new EnumModel("ND", "NorthDakota");
    public static final EnumModel OH = new EnumModel("OH", "Ohio");
    public static final EnumModel OK = new EnumModel("OK", "Oklahoma");
    public static final EnumModel OR = new EnumModel("OR", "Oregon");
    public static final EnumModel PA = new EnumModel("PA", "Pennsylvania");
    public static final EnumModel RI = new EnumModel("Name", "RhodeIsland");
    public static final EnumModel SC = new EnumModel("SC", "SouthCarolina");
    public static final EnumModel SD = new EnumModel("SD", "SouthDakota");
    public static final EnumModel TN = new EnumModel("TN", "Tennessee");
    public static final EnumModel TX = new EnumModel("TX", "Texas");
    public static final EnumModel UT = new EnumModel("UT", "Utah");
    public static final EnumModel VT = new EnumModel("VT", "Vermont");
    public static final EnumModel VA = new EnumModel("VA", "Virginia");
    public static final EnumModel WA = new EnumModel("WA", "Washington");
    public static final EnumModel WV = new EnumModel("WV", "WestVirginia");
    public static final EnumModel WI = new EnumModel("WI", "Wisconsin");
    public static final EnumModel WY = new EnumModel("WY", "Wyoming");
    public static final EnumModel AS = new EnumModel("AS", "AmericanSamoa");
    public static final EnumModel FM = new EnumModel("FM", "FederatedStatesofMicronesia");
    public static final EnumModel GU = new EnumModel("GU", "Guam");
    public static final EnumModel MH = new EnumModel("MH", "MarshallIslands");
    public static final EnumModel MP = new EnumModel("MP", "NorthernMarianaIslands");
    public static final EnumModel PW = new EnumModel("PW", "Palau");
    public static final EnumModel PR = new EnumModel("PR", "PuertoRico");
    public static final EnumModel VI = new EnumModel("VI", "VirginIslands");
    public static final EnumModel AA = new EnumModel("AA", "ArmedForcesAmericas");
    public static final EnumModel AE = new EnumModel("AE", "ArmedForcesEurope");
    public static final EnumModel AP = new EnumModel("AP", "ArmedForcesPacific");

    public static ArrayList<EnumModel> getStates() {
        return new ArrayList<>() {{
            add(AL);
            add(AK);
            add(AZ);
            add(AR);
            add(CA);
            add(CO);
            add(CT);
            add(DE);
            add(DC);
            add(FL);
            add(GA);
            add(HI);
            add(ID);
            add(IL);
            add(IN);
            add(IA);
            add(KS);
            add(KY);
            add(LA);
            add(ME);
            add(MD);
            add(MA);
            add(MI);
            add(MN);
            add(MS);
            add(MO);
            add(MT);
            add(NE);
            add(NV);
            add(NH);
            add(NJ);
            add(NM);
            add(NY);
            add(NC);
            add(ND);
            add(OH);
            add(OK);
            add(OR);
            add(PA);
            add(RI);
            add(SC);
            add(SD);
            add(TN);
            add(TX);
            add(UT);
            add(VT);
            add(VA);
            add(WA);
            add(WV);
            add(WI);
            add(WY);
            add(AS);
            add(FM);
            add(GU);
            add(MH);
            add(MP);
            add(PW);
            add(PR);
            add(VI);
            add(AA);
            add(AE);
            add(AP);
        }};
    }

}